version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /nginx.conf

    depends_on:
      - service-logic
      - service-database

  service-logic:
    build:
      context: ./service-logic
    ports:
      - "3000:3000"

    depends_on:
      - service-database

  service-database:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expressdb
      MYSQL_USER: expressuser
      MYSQL_PASSWORD: expresspassword
    ports:
      - "3306:3306"
